### ISSUE TITLE
スマホ対応

### ISSUE THREAD

**Issue by ytanaka-** [ytanaka-/menthas#13]
- ios
- android

ニュースといえばスマホアプリ。まずはandroidか？

**Comment by ytanaka-** [comment]
必須な感ある

**Comment by ken5scal** [comment]
お待ちしております！（私も作りたい）

**Comment by ytanaka-** [comment]
リニューアル後にアプリではないけど簡単ではあるがPWAにしてスマホ対応したので一旦Close
